export {default as NavAdmin} from "./NavAdmin"
export  {default as FilterProductSection } from "./products/FilterProductSection"
export  {default as FilterCustomerSection } from "./customers/FilterCustomerSection"
export  {default as FilterInventorySection } from "./inventory/FilterInventorySection"
export {default as ProductsTbl} from "./products/ProductsTbl" 
export {default as CustomersTbl} from "./customers/CustomersTbl" 
export { default as InventoryTbl} from "./inventory/InventoryTbl"
export {default as ProvidersTbl} from "./providers/ProvidersTbl" 
export {default as BrandsTbl} from "./brands/BrandsTbl" 
export {default as CategoriesTbl } from "./categories/CategoriesTbl"